package com.about.kby;

import com.about.kby.model.UserModel;

public class ProductConfig {
    public static String baseUrl = "https://minswaysolutions.com/webteam/kby/api/";
    public static String userlogin = (baseUrl + "userlogin.php");
    public static UserModel userModel = new UserModel();
    public static String userotpverify = (baseUrl + "userotpverify.php");
    public static String eucationopencirclelist = (baseUrl + "eucationopencirclelist.php");
    public static String checklist_openlist = (baseUrl + "checklist_openlist.php");
    public static String checklist_group_list = (baseUrl + "checklist_group_list.php");
    public static String profile = (baseUrl + "profile_update.php");
    public static String check_list_input = (baseUrl + "check_list_input.php");
    public static String datelist_check = (baseUrl + "datelist_check.php");
    public static String statuschecklist = (baseUrl + "statuschecklist.php");
    public static String update_date = (baseUrl + "update_date.php");
    public static String removepersonal = (baseUrl + "removepersonal.php");
    public static String removeeduca = (baseUrl + "removeeduca.php");
    public static String edu_exit_grp = (baseUrl + "edu_exit_grp.php");
    public static String delete_task = (baseUrl + "delete_task.php");
    public static String personal_user_input_fetch = (baseUrl + "personal_user_input_fetch.php");
    public static String personal_user_Insights_fetch = (baseUrl + "personal_user_Insights_fetch.php");
    public static String personal_user_input_insert = (baseUrl + "personal_user_input_insert.php");
    public static String category = (baseUrl + "category.php");
    public static String updatesubjectdurin = (baseUrl + "updatesubjectdurin.php");
    public static String opencircle_update = (baseUrl + "opencircle_update.php");
    public static String kby_groupinsert = (baseUrl + "kby_groupinsert.php");
    public static String education_group = (baseUrl + "education_group.php");
    public static String checklist_groups = (baseUrl + "checklist_groups.php");
    public static String subjectopencircle = (baseUrl + "subjectopencircle.php");
    public static String checklist_open = (baseUrl + "checklist_open.php");
    public static String menu = (baseUrl + "menu.php");
    public static String kby_group_list = (baseUrl + "kby_group_list.php");
    public static String education_group_list = (baseUrl + "education_group_list.php");
    public static String subcategory = (baseUrl + "subcategory.php");
    public static String subject_add = (baseUrl + "subject_add.php");
    public static String education_new = (baseUrl + "education_grp_add.php");
    public static String education_delete = (baseUrl + "education_grp_del.php");
    public static String subjectlist = (baseUrl + "subjectlist.php");
    public static String education_exist = (baseUrl + "education_grp_fetch.php");
    public static String education_grp_add = (baseUrl + "education_grp_mem_add.php");
    public static String checklistmultiple = (baseUrl + "checklistmultiple.php");
    public static String education_grp_update = (baseUrl + "education_grp_update.php");
    public static String education_input = (baseUrl + "education_grp_sub_fetch.php");
    public static String tasklist = (baseUrl + "tasklist.php");
    public static String countlist = (baseUrl + "countlist.php");
    public static String education_grp_fetch = (baseUrl + "education_grp_mem_fetch.php");
    public static String education_grp_delete = (baseUrl + "education_grp_mem_del.php");
    public static String checklist_add = (baseUrl + "check_list_add.php");
    public static String checklist_fetch = (baseUrl + "check_list_fetch.php");
    public static String checklist_update = (baseUrl + "check_list_update.php");
    public static String checklist_delete = (baseUrl + "check_list_del.php");
    public static String personal_new = (baseUrl + "personal_grp_add.php");
    public static String personal_exist = (baseUrl + "personal_grp_fetch.php");
    public static String personal_grp_update = (baseUrl + "personal_grp_update.php");
    public static String personal_delete = (baseUrl + "personal_grp_delete.php");
    public static String personal_grp_add = (baseUrl + "personal_grp_member_add.php");
    public static String personal_grp_fetch = (baseUrl + "personal_grp_member_fetch.php");
    public static String personal_grp_delete = (baseUrl + "personal_grp_member_del.php");
}
